-- +migrate Up
ALTER TABLE "products"
ADD COLUMN IF NOT EXISTS "brand_id" UUID,
ADD COLUMN IF NOT EXISTS "product_category_id" UUID,
ADD COLUMN IF NOT EXISTS "tags" VARCHAR,
ADD COLUMN IF NOT EXISTS "lifetime" TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "maintenance_interval" INT,
ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMP WITH TIME ZONE;

-- +migrate Down
ALTER TABLE "products"
DROP COLUMN IF EXISTS "brand_id",
DROP COLUMN IF EXISTS "product_category_id",
DROP COLUMN IF EXISTS "tags",
DROP COLUMN IF EXISTS "lifetime",
DROP COLUMN IF EXISTS "maintenance_interval",
DROP COLUMN IF EXISTS "created_at",
DROP COLUMN IF EXISTS "updated_at",
DROP COLUMN IF EXISTS "deleted_at";
