-- +migrate Up
ALTER TABLE "companies"
ADD COLUMN IF NOT EXISTS "type" INT,
ADD COLUMN IF NOT EXISTS "address" VARCHAR,
ADD COLUMN IF NOT EXISTS "phone_number" VARCHAR,
ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "deleted_at" TIMESTAMP WITH TIME ZONE;

-- +migrate Down
ALTER TABLE "companies"
DROP COLUMN IF EXISTS "type",
DROP COLUMN IF EXISTS "address",
DROP COLUMN IF EXISTS "phone_number",
DROP COLUMN IF EXISTS "created_at",
DROP COLUMN IF EXISTS "updated_at",
DROP COLUMN IF EXISTS "deleted_at";
