-- +migrate Up
ALTER TABLE "assets"
ADD COLUMN IF NOT EXISTS "qty" VARCHAR,
ADD COLUMN IF NOT EXISTS "terminal_id" VARCHAR,
ADD COLUMN IF NOT EXISTS "location_name" VARCHAR,
ADD COLUMN IF NOT EXISTS "location_identity" INT,
ADD COLUMN IF NOT EXISTS "address" VARCHAR,
ADD COLUMN IF NOT EXISTS "administrative_area" VARCHAR,
ADD COLUMN IF NOT EXISTS "latitude" VARCHAR,
ADD COLUMN IF NOT EXISTS "longitude" VARCHAR,
ADD COLUMN IF NOT EXISTS "altitude" VARCHAR,
ADD COLUMN IF NOT EXISTS "location_time_and_access" VARCHAR,
ADD COLUMN IF NOT EXISTS "pic_location" VARCHAR,
ADD COLUMN IF NOT EXISTS "pic_area" VARCHAR,
ADD COLUMN IF NOT EXISTS "phone_number" VARCHAR,
ADD COLUMN IF NOT EXISTS "day" VARCHAR,
ADD COLUMN IF NOT EXISTS "hour" VARCHAR,
ADD COLUMN IF NOT EXISTS "main_energy_source" VARCHAR,
ADD COLUMN IF NOT EXISTS "alternative_energy_source" VARCHAR,
ADD COLUMN IF NOT EXISTS "extra_information" VARCHAR,
ADD COLUMN IF NOT EXISTS "minimum_voltage" VARCHAR,
ADD COLUMN IF NOT EXISTS "maximum_voltage" VARCHAR,
ADD COLUMN IF NOT EXISTS "grounding_n_to_g" VARCHAR,
ADD COLUMN IF NOT EXISTS "electrical_equipment_available_in_location" VARCHAR,
ADD COLUMN IF NOT EXISTS "lc_provide" VARCHAR,
ADD COLUMN IF NOT EXISTS "satelitte_name" VARCHAR,
ADD COLUMN IF NOT EXISTS "spot_beam" VARCHAR,
ADD COLUMN IF NOT EXISTS "operation_band" INT,
ADD COLUMN IF NOT EXISTS "vsat_system" INT,
ADD COLUMN IF NOT EXISTS "modem_brand" VARCHAR,
ADD COLUMN IF NOT EXISTS "modem_type" VARCHAR,
ADD COLUMN IF NOT EXISTS "modem_sn" VARCHAR,
ADD COLUMN IF NOT EXISTS "antenna_diameter" VARCHAR,
ADD COLUMN IF NOT EXISTS "antenna_brand" VARCHAR,
ADD COLUMN IF NOT EXISTS "antenna_type" VARCHAR,
ADD COLUMN IF NOT EXISTS "antenna_sn" VARCHAR,
ADD COLUMN IF NOT EXISTS "sspa_buc" VARCHAR,
ADD COLUMN IF NOT EXISTS "sspa_buc_brand" VARCHAR,
ADD COLUMN IF NOT EXISTS "sspa_buc_type" VARCHAR,
ADD COLUMN IF NOT EXISTS "sspa_buc_sn" VARCHAR,
ADD COLUMN IF NOT EXISTS "l_n_b_brand" VARCHAR,
ADD COLUMN IF NOT EXISTS "l_n_b_type" VARCHAR,
ADD COLUMN IF NOT EXISTS "l_n_b_sn" VARCHAR,
ADD COLUMN IF NOT EXISTS "switch_type" VARCHAR,
ADD COLUMN IF NOT EXISTS "switch_brand" VARCHAR,
ADD COLUMN IF NOT EXISTS "switch_sn" VARCHAR,
ADD COLUMN IF NOT EXISTS "ipmanagement_modem" VARCHAR,
ADD COLUMN IF NOT EXISTS "ipmodem" VARCHAR,
ADD COLUMN IF NOT EXISTS "iprouter" VARCHAR,
ADD COLUMN IF NOT EXISTS "ipap_1" VARCHAR,
ADD COLUMN IF NOT EXISTS "ipap_2" VARCHAR,
ADD COLUMN IF NOT EXISTS "user_type" INT,
ADD COLUMN IF NOT EXISTS "antenna_location" VARCHAR,
ADD COLUMN IF NOT EXISTS "antenna_location_type" INT,
ADD COLUMN IF NOT EXISTS "antenna_pedestal_type" VARCHAR,
ADD COLUMN IF NOT EXISTS "indoor_unit_location" VARCHAR,
ADD COLUMN IF NOT EXISTS "indoor_unit" VARCHAR,
ADD COLUMN IF NOT EXISTS "supporting_parts" VARCHAR,
ADD COLUMN IF NOT EXISTS "outdoor_ap1location" VARCHAR,
ADD COLUMN IF NOT EXISTS "outdoor_ap_1_type" VARCHAR,
ADD COLUMN IF NOT EXISTS "outdoor_ap_1_brand" VARCHAR,
ADD COLUMN IF NOT EXISTS "outdoor_ap_1_sn" VARCHAR,
ADD COLUMN IF NOT EXISTS "outdoor_ap_1_range" VARCHAR,
ADD COLUMN IF NOT EXISTS "outdoor_ap_1_audience" VARCHAR,
ADD COLUMN IF NOT EXISTS "outdoor_ap_1_security" VARCHAR,
ADD COLUMN IF NOT EXISTS "outdoor_ap_1_duration_settings_bandwidth_cos" VARCHAR,
ADD COLUMN IF NOT EXISTS "outdoor_ap_2_location" VARCHAR,
ADD COLUMN IF NOT EXISTS "outdoor_ap_2_type" VARCHAR,
ADD COLUMN IF NOT EXISTS "outdoor_ap_2_brand" VARCHAR,
ADD COLUMN IF NOT EXISTS "outdoor_ap_2_sn" VARCHAR,
ADD COLUMN IF NOT EXISTS "outdoor_ap_2_range" VARCHAR,
ADD COLUMN IF NOT EXISTS "outdoor_ap_2_audience" VARCHAR,
ADD COLUMN IF NOT EXISTS "outdoor_ap_2_security" VARCHAR,
ADD COLUMN IF NOT EXISTS "outdoor_ap_2_duration_settings_bandwidth_cos" VARCHAR,
ADD COLUMN IF NOT EXISTS "power_stabilizer_brand" VARCHAR,
ADD COLUMN IF NOT EXISTS "power_stabilizer_type" VARCHAR,
ADD COLUMN IF NOT EXISTS "power_stabilizer_sn" VARCHAR,
ADD COLUMN IF NOT EXISTS "rack_brand" VARCHAR,
ADD COLUMN IF NOT EXISTS "rack_type" VARCHAR,
ADD COLUMN IF NOT EXISTS "rack_sn" VARCHAR,
ADD COLUMN IF NOT EXISTS "notes" VARCHAR;

-- +migrate Down
ALTER TABLE "assets"
DROP COLUMN IF EXISTS "terminal_id",
DROP COLUMN IF EXISTS "location_name",
DROP COLUMN IF EXISTS "location_identity",
DROP COLUMN IF EXISTS "address",
DROP COLUMN IF EXISTS "administrative_area",
DROP COLUMN IF EXISTS "latitude",
DROP COLUMN IF EXISTS "longitude",
DROP COLUMN IF EXISTS "altitude",
DROP COLUMN IF EXISTS "location_time_and_access",
DROP COLUMN IF EXISTS "pic_location",
DROP COLUMN IF EXISTS "pic_area",
DROP COLUMN IF EXISTS "phone_number",
DROP COLUMN IF EXISTS "day",
DROP COLUMN IF EXISTS "hour",
DROP COLUMN IF EXISTS "main_energy_source",
DROP COLUMN IF EXISTS "alternative_energy_source",
DROP COLUMN IF EXISTS "extra_information",
DROP COLUMN IF EXISTS "minimum_voltage",
DROP COLUMN IF EXISTS "maximum_voltage",
DROP COLUMN IF EXISTS "grounding_n_to_g",
DROP COLUMN IF EXISTS "electrical_equipment_available_in_location",
DROP COLUMN IF EXISTS "lc_provide",
DROP COLUMN IF EXISTS "satelitte_name",
DROP COLUMN IF EXISTS "spot_beam",
DROP COLUMN IF EXISTS "operation_band",
DROP COLUMN IF EXISTS "vsat_system",
DROP COLUMN IF EXISTS "modem_brand",
DROP COLUMN IF EXISTS "modem_type",
DROP COLUMN IF EXISTS "modem_sn",
DROP COLUMN IF EXISTS "antenna_diameter",
DROP COLUMN IF EXISTS "antenna_brand",
DROP COLUMN IF EXISTS "antenna_type",
DROP COLUMN IF EXISTS "antenna_sn",
DROP COLUMN IF EXISTS "sspa_buc",
DROP COLUMN IF EXISTS "sspa_buc_brand",
DROP COLUMN IF EXISTS "sspa_buc_type",
DROP COLUMN IF EXISTS "sspa_buc_sn",
DROP COLUMN IF EXISTS "l_n_b_brand",
DROP COLUMN IF EXISTS "l_n_b_type",
DROP COLUMN IF EXISTS "l_n_b_sn",
DROP COLUMN IF EXISTS "switch_type",
DROP COLUMN IF EXISTS "switch_brand",
DROP COLUMN IF EXISTS "switch_sn",
DROP COLUMN IF EXISTS "ipmanagement_modem",
DROP COLUMN IF EXISTS "ipmodem",
DROP COLUMN IF EXISTS "iprouter",
DROP COLUMN IF EXISTS "ipap_1",
DROP COLUMN IF EXISTS "ipap_2",
DROP COLUMN IF EXISTS "user_type",
DROP COLUMN IF EXISTS "antenna_location",
DROP COLUMN IF EXISTS "antenna_location_type",
DROP COLUMN IF EXISTS "antenna_pedestal_type",
DROP COLUMN IF EXISTS "indoor_unit_location",
DROP COLUMN IF EXISTS "indoor_unit",
DROP COLUMN IF EXISTS "supporting_parts",
DROP COLUMN IF EXISTS "outdoor_ap1location",
DROP COLUMN IF EXISTS "outdoor_ap_1_type",
DROP COLUMN IF EXISTS "outdoor_ap_1_brand",
DROP COLUMN IF EXISTS "outdoor_ap_1_sn",
DROP COLUMN IF EXISTS "outdoor_ap_1_range",
DROP COLUMN IF EXISTS "outdoor_ap_1_audience",
DROP COLUMN IF EXISTS "outdoor_ap_1_security",
DROP COLUMN IF EXISTS "outdoor_ap_1_duration_settings_bandwidth_cos",
DROP COLUMN IF EXISTS "outdoor_ap_2_location",
DROP COLUMN IF EXISTS "outdoor_ap_2_type",
DROP COLUMN IF EXISTS "outdoor_ap_2_brand",
DROP COLUMN IF EXISTS "outdoor_ap_2_sn",
DROP COLUMN IF EXISTS "outdoor_ap_2_range",
DROP COLUMN IF EXISTS "outdoor_ap_2_audience",
DROP COLUMN IF EXISTS "outdoor_ap_2_security",
DROP COLUMN IF EXISTS "outdoor_ap_2_duration_settings_bandwidth_cos",
DROP COLUMN IF EXISTS "power_stabilizer_brand",
DROP COLUMN IF EXISTS "power_stabilizer_type",
DROP COLUMN IF EXISTS "power_stabilizer_sn",
DROP COLUMN IF EXISTS "rack_brand",
DROP COLUMN IF EXISTS "rack_type",
DROP COLUMN IF EXISTS "rack_sn",
DROP COLUMN IF EXISTS "notes";
