version: "3"
services:
    database:
        image: cockroachdb/cockroach
        command: start-single-node --insecure
        ports:
            - "8080:8080"
            - "26257:26257"
        volumes:
            - ".docker/cockroach:/cockroach/cockroach-data"
    redis:
        image: bitnami/redis:latest
        environment:
            - REDIS_PASSWORD=secret123
        ports:
            - "6379:6379"
        volumes:
            - ".docker/redis:/bitnami/redis/data"
    nats:
        image: "nats:0.8.0"
        entrypoint: "/gnatsd -DV"
        ports:
            - "4222:4222"
            - "8222:8222"
    neo4j:
        image: neo4j:4.2.1
        network_mode: "bridge"
        ports:
            - "7474:7474"
            - "7687:7687"
        environment:
            - NEO4J_dbms_security_procedures_unrestricted=apoc.*
            - NEO4J_apoc_import_file_enabled=true
            - NEO4J_dbms_shell_enabled=true
        volumes:
            - ./plugins:/plugins
            - ./data:/data
            - ./import:/import
            - ./ssl:/ssl
            - ./conf/:/conf
